{% set name = "bvalcalc" %}
{% set version = "0.7.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c46450a7cf5777d40f35683553935ea70d2af5e235195a87df03aae8f50bce6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - bvalcalc = Bvalcalc.cli:main
    - Bvalcalc = Bvalcalc.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - scipy >=1.13
    - matplotlib-base
    - seaborn >=0.13.2,<0.14.0

test:
  imports:
    - Bvalcalc
    - Bvalcalc.core
    - Bvalcalc.utils
  commands:
    - pip check
    - bvalcalc --help
    - Bvalcalc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JohriLab/Bvalcalc
  license: GPL-3.0-only
  license_file: LICENSE
  license_family: GPL
  summary: Calculate relative diversity (B) under background selection
  doc_url: https://JohriLab.github.io/Bvalcalc/
  dev_url: https://github.com/JohriLab/Bvalcalc

extra:
  recipe-maintainers:
    - jacobimarsh
